In [18]:
import numpy as np

# Create a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)
print (np.std(arr_2d))

[[1 2 3]
 [4 5 6]]
1.707825127659933


In [19]:
import numpy as np

# Create a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)
print (np.std(arr_2d))

a = np.array([2, 2, 3, 9, 5])
b = np.array([6, 7, 8, 9, 10])

combined = np.concatenate((a, b))

c = a + b 
print(c)  # Output: [ 7  9 11 13 15]

both_even = (a % 2 == 0) | (b % 2 == 0)
print(both_even)  # Output: [False False True False True]

odd_in_combined = (combined % 2 != 0)  #odd
oddand_great_than_2 = np.logical_and(odd_in_combined, combined > 2)

print(oddand_great_than_2) # Output: [False False  True  True  True False  True False  True False]




[ 8  9 11 18 15]
[ True  True  True False  True]
[False False  True  True  True False  True False  True False]
